name: zaracast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  convert: ^3.1.1
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.8
  form_validator: ^2.1.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  material_color_utilities: ^0.8.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.0
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/