import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:zaracast/src/core/themes/base_material_theme.dart';
import 'package:zaracast/src/core/themes/ghost_spider_material_theme.dart';
import 'package:zaracast/src/core/themes/hulk_material_theme.dart';
import 'package:zaracast/src/core/themes/iron_man_material_theme.dart';

/// Body font name
const bodyFontString = 'Red Hat Text';

/// Display font name
const displayFontString = 'Red Hat Display';

/// Build a [TextTheme].
///
/// The [TextTheme] must use the [GoogleFonts] package to load the fonts.
///
/// The [bodyFontString] and [displayFontString] are the font names used in the
/// [GoogleFonts] package. Example: 'Red Hat Text', 'Red Hat Display'.
///
/// This method was copied from the Flutter export generated by the Material
/// Theme Builder website:
/// https://material-foundation.github.io/material-theme-builder/
TextTheme buildTextTheme(
  BuildContext context,
  String bodyFontString,
  String displayFontString,
) {
  final baseTextTheme = Theme.of(context).textTheme;
  final bodyTextTheme = GoogleFonts.getTextTheme(bodyFontString, baseTextTheme);
  final displayTextTheme =
      GoogleFonts.getTextTheme(displayFontString, baseTextTheme);
  final textTheme = displayTextTheme.copyWith(
    bodyLarge: bodyTextTheme.bodyLarge,
    bodyMedium: bodyTextTheme.bodyMedium,
    bodySmall: bodyTextTheme.bodySmall,
    labelLarge: bodyTextTheme.labelLarge,
    labelMedium: bodyTextTheme.labelMedium,
    labelSmall: bodyTextTheme.labelSmall,
  );

  return textTheme;
}

/// Material theme names.
///
/// This will also be the name of the theme that the user sees in the app.
enum MaterialTheme { ghostSpider, ironMan, hulk }

/// Build Material themes.
///
/// Each [MaterialTheme] enum is mapped to the corresponding
/// [BaseMaterialTheme] class.
Map<MaterialTheme, BaseMaterialTheme> buildThemes(TextTheme textTheme) => {
      MaterialTheme.ghostSpider: GhostSpiderMaterialTheme(textTheme),
      MaterialTheme.ironMan: IronManMaterialTheme(textTheme),
      MaterialTheme.hulk: HulkMaterialTheme(textTheme),
    };
